### ISSUE TITLE
Specify semantics for 2D column-vectors and row-vectors

### ISSUE THREAD

**Issue by astanin** [mikera/core.matrix#96] opened 2014-01-07 16:42 UTC
I'm writing an implementation of core.matrix for EJML, and noticed that the approaches to column-vector and row-vectors are not consistent across the API.

On one hand, core.matrix' `equals` considers a row vector and its transpose to be different:

``` clojure
user=> (equals [1 2 3] [[1][2][3]])
false
```

On the other hand, `mmul` is happy to take whatever vector shape, and returns a row vector:

``` clojure
user=> (mmul [[1 2][3 4]] [10 100])
[210 430]
```

This behaviour is enforced by [test-diagonal (compliance_tester.clj:568)](https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/compliance_tester.clj#L568). It's similar to how NumPy behaves, it's convenient, but, strictly speaking, it is not correct.

The liberty of transposing vectors shouldn't be enforced on all implementations, particularly those which distinguish column-vectors and row-vectors. EJML happens to be such an imlpementation, where all vectors are represented by matrices. Naturally, the result of matrix-vector multiplication is a column vector and _doesn't pass tests_ (test-diagonal):

``` clojure
user=> (mmul (matrix :ejml-dense-64bit [[1 2][3 4]]) [10 100])
#<DenseMatrix64F Type = dense , numRows = 2 , numCols = 1
210.000  
430.000  
>
```

Surprisingly, the vector-based implementation may output column vectors too:

``` clojure
user=> (mmul [[1 2][3 4]] [[10][100]])
[[210] [430]]
```

As an implementer I have a choice between:
- tweak multiplication output to mimic that of the persistent vector implementation (sounds like accidental complexity to me, and lots unnecessary runtime checks)
- tweak `equals` method to consider row-vectors and column-vectors the same (it would be wrong and inconsistent with how the default implementation works)
- ask to modify the tests and/or specify precisely what is the expected behaviour of API methods when working with vectors.

**Comment by astanin** [comment] 2014-01-07 17:04
The suggested change to the tests is:

``` diff
diff --git a/src/main/clojure/clojure/core/matrix/compliance_tester.clj b/src/main/clojure/clojure/core/matrix/compliance_tester.clj
index 8e7218b..d7fe8c5 100644
--- a/src/main/clojure/clojure/core/matrix/compliance_tester.clj
+++ b/src/main/clojure/clojure/core/matrix/compliance_tester.clj
@@ -567,3 +567,3 @@
         I-squared (diagonal-matrix im [1 4 9])]
-    (is (equals [1 4 9] (mmul I [1 2 3])))
+    (is (equals [[1] [4] [9]] (mmul I [[1] [2] [3]])))
     (is (equals I-squared (mmul I I)))
```

The default implementation passes it, other implementations will be allows to return a column-vector from `mmul`.

**Comment by mikera** [comment] 2014-01-07 18:47
Hi Sergey,

Great that you're working with EJML! It's a cool library, I've been hoping to test it out with core.matrix for a while.

You have hit upon an interesting and important topic, so I'll try my best to explain the situation as I see it.

EJML column vectors and row vectors both should be represented as 2D matrices in `core.matrix` terms : i.e. either as Nx1 or 1xN matrices respectively.

This topic has been discussed a few times in the Numerical Clojure group. It boils down to there being two different perspectives:
- The **array programming** viewpoint, where all possible shapes of array are supported: in this case 1D vectors are a distinct type and don't have a row/column distinction
- The **mathematical matrix** viewpoint, where everything is a 2D matrix. "Row vectors" and "column vectors" are really 1xN and Nx1 matrices in terms of their behaviour.

`core.matrix` actually supports both perspectives, the only thing you have to do is treat everything as 2D if you want the second perspective (which sounds like it is the best fit for EJML....)

If you do this then `mmul` should work as you expect (as will many other functions like `transpose` etc.)

Incidentally, I don't think it's possible to obtain a logically consistent set of array operations if you try to differentiate between row-oriented and column-oriented 1D vectors: you have to treat them as 2D to make the maths work.

The reason for this test result is a good illustration:

``` clojure
(equals [1 2 3] [[1][2][3]])
=> false
```

this isn't comparing a vector with its transpose: it's comparing a vector with a Nx1 matrix. Which are by definition not equal because they have different shapes. The following however are valid comparisons:

``` clojure
;; a row matrix is equal to the transpose of a column matrix
(equals [[1 2 3]] (transpose [[1][2][3]]))
=> true

;; a 1D vector is equal to the transpose of itself
(equals [1 2 3] (transpose [1 2 3]))
=> true
```

Hopefully this helps to clarify things?

**Comment by astanin** [comment] 2014-01-07 23:37
The problem is I cannot write a sensible implementation for EJML to pass core.matrix tests unless I mimic exactly the behaviour of the vector-based implementation.

Internally, I treat everything like a 2D matrix (mathematical matrix viewpoint). Only dimensionality 2 is supported. A 1-dimensional sequence is coerced to a N×1 matrix when necessary. Unfortunately, that is not enough to pass the compliance tests: any 2D implementation is currently _required_ to interoperate with 1D vectors, in a particular (non-mathematical) way.

Let's take the test I mentioned above (https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/compliance_tester.clj#L568)

```
  (let [I (diagonal-matrix im [1 2 3])
        I-squared (diagonal-matrix im [1 4 9])]
    (is (equals [1 4 9] (mmul I [1 2 3])))
```

To pass it, the implementation should
- implement matrix-vector multiplication. It may
  - either coerce `[1 2 3]` to the type of `I`, i.e. a 2D N×1 matrix
  - or define a special case of matrix-vector operations everywhere
- implement vector-matrix equality. To pass the test as it's written _every_ implementation is required to
  - coerce an N×1 matrix to a 1D vector
- implement matrix-vector equality symmetrically
  - it's a special case for vectors again

Let me show why vector-matrix equality is a problem for me right now.

```
user=> v
#<DenseMatrix64F Type = dense , numRows = 3 , numCols = 1
 1.000  
 2.000  
 3.000  
>
user=> (equals v [1 2 3])
true
user=> (equals [1 2 3] v)
false
```

Equality depends on coercion, and coercion is not working the same in both directions.

```
user=> (coerce [] v)
[[1.0] [2.0] [3.0]]
user=> (coerce v [1 2 3])
#<DenseMatrix64F Type = dense , numRows = 3 , numCols = 1
 1.000 
 2.000  
 3.000  
>
```

I may change `coerce` and `to-nested-vectors` so that they return 1D vectors whenever possible. I'll have to adjust `equals`, `mmul` and many other methods to add run-time checks and handle 1D operands separately. The implementation will be roughly twice as complex, and probably slower than it could be. Eventually, I can do it and pass the tests, but I don't like it this way.

So I kindly ask,

1) is it possible to modify some tests from `matrix-tests-2d` so that they do not require interoperability with 1D vectors (like the change above; I may take care of it and prepare a PR if you like the idea)
2) or, if you consider matrix-vector interop essential even for 2D-only implementations, do you mind specifying how exactly the conversions between N×1, 1×N matrices and 1D vectors are supposed to be made (test cases would be helpful)

I also wondered if some policy about 1D vectors in 2D context can be pronounced. For example, I often think about 1D NumPy arrays as column-vectors (N×1) written horizontally: it doesn't have to be transposed in a matrix-vector product, and the result is the same shape again.

**Comment by mikera** [comment] 2014-01-08 01:43
I guess it's fine if you want to conditionally disable some tests for implementations that don't support 1D vectors (this is what the supports-dimensionality? protocol function was intended for.....). Happy to take a PR for that

Still, the implementation would be better if it supported 1D vectors - mainly because this enhances the flexibility to perform generalised array operations and interoperate with other implementations (remember: you don't strictly need to return EJML types, any other 1D type such as a a double[] array will do....)

I think we're pretty consistent with NumPy in most of these regards - our 1D vectors are pretty much identically defined to NumPy 1D vectors.

Either way, this is a problem:

``` clojure
;; with v as a 3x1 EJML matrix
(equals v [1 2 3])
=> true
```

Result here should be false: since the shapes don't match. You shouldn't be trying to implement coerce in a way that converts a 1D vector into a 2D matrix shape - that's definitely going to be a logical error (the broadcasting operations can do this, but they are special....). 

A smart implementation for equals should be something like:
- check if shapes are equal. if not, then return false
- only if shapes are equal, iterate over arrays to check that all elements are equal

**Comment by astanin** [comment] 2014-01-08 10:27
> You shouldn't be trying to implement coerce in a way that converts a 1D vector into a 2D matrix shape

Thanks for explaining coercion. I find the docstring of PCoercion too vague (what exactly is coerce supposed to do? convert element types? convert shapes? Now I see that it's obviously not about shape).

> A smart implementation for equals should be something like:
> -   check if shapes are equal. if not, then return false
> -   only if shapes are equal, iterate over arrays to check that all elements are equal

That's what I've written initially, but then I couldn't pass equality between a 1D vector and a 2D colum-vector. I'll write an interop layer implementation to be partially compatible (see below) with the existing 1D behaviour, and I'll fix the tests to not require it from future 2D-only implementations.

So the things I learned from our discussion so far:
- 1D vectors, N×1, and 1×N matrices (column and row vectors) are three different shapes and should never be equal.
- `coerce` should never change the shape.
- the implementation would be better to support 1D vectors, though it's not required to (the tests may be changed).

Thanks for making it clear.

I see no problem in taking 1D arguments (like in `(mmul some-ejml-mat [1 2 3])`). I consider returning 1D arguments to be a more delicate matter. Let's consider the `main-diagonal` method. EJML can do it efficiently, and returns a 2D column-vector (or I may transpose it to produce a row-vector). So, the result is 2D. I believe, that to benefit from EJML performance it's better to keep it as is, but then the method has to pass `test-diagonal`:

``` clojure
(is (equals [1 5 9] (main-diagonal m))
```

Given what you say about coercion and equality in core.matrix, it can never pass. As we do not state equivalence between 1D and some 2D shapes, nor change shape on coercion/to-nested-vectors, the tests like this should be amended too. _What do you think about writing such tests like this_:

``` clojure
(is (or (equals [1 5 9] (main-diagonal m))
        (equals [[1][5][9]] (main-diagonal m))))
```

Implementations which have a 1D representations (like persistent vectors) will be still allowed to return a 1D result. Implementations which do not have a 1D representation (like EJML) will be allowed to return a column vector. Pro: every implementation may choose its native and most efficient representation; fewer intermediate objects will be created in the typical code; we'll avoid lots of data-copying. Contra: we'll never know what `main-diagonal` returns. 

I don't see how this dilemma may be solved without postulating some shape equivalence rules or introducing a function which simplifies shape (removes all dimensions of size 1). Any ideas?

**Comment by mikera** [comment] 2014-01-08 11:18
`main-diagonal` needs to return a 1D vector: that's part of the contract. We have to be quite strict about this, otherwise people can't depend on the array abstraction.

However there are at least three good ways around this:
- You don't need to return an EJML matrix: a double[] vector is fine (and in fact probably even more efficient than an EJML matrix). I'm pretty sure EJML provides an easy way to get that the underlying double array - there's a `getData()` method, right?
- You could fake a 1D vector by using a wrapper class that wraps a 2D row or column matrix. This is what Clatrix does internally to get around the similar problem that JBlas only has 2D matrices
- Don't implement main-diagonal at all: the default implementation should do it for you. This will cost a bit of performance, but that can be improved later if it becomes a bottleneck.

If you have a separate requirement that is equivalent to `main-diagonal` but requires a 2D matrix then that is interesting - but the way to handle it would probably be to write a custom function, or just do:

``` clojure
(row-matrix (main-diagonal M))
```

If `main-diagonal` returns a `double[]`, and `row-matrix` just wraps it up again in an EJML matrix, then that's going to be pretty as efficient as anything else (one extra protocol, one lightweight object construction....)

**Comment by astanin** [comment] 2014-01-08 11:29
Yes, there is a way to get the double[] array directly. It doesn't seem possible to (re)create a new EJML matrix from a double[] array without copying data. It's possible to construct it from a double[][] array, but I suspect it copies data anyway.

Well, if it's part of the contract, it's part of the contract.

**Comment by mikera** [comment] 2014-01-08 11:40
Might be worth an issue / PR to EJML? Not sure what they are like at accepting contributions, but a `wrap` function for wrapping double arrays without copying is pretty handy.

**Comment by mikera** [comment] 2014-03-27 08:03
Closing this as I don't think there is any outstanding open action

**Closed as completed by mikera** 2014-03-27 08:03 UTC
Labels: question
