### ISSUE TITLE
Inconsistent element-wise equality semantics

### ISSUE THREAD

**Issue by RadicalZephyr** [mikera/core.matrix#245] opened 2015-08-23 19:52 UTC
I think the equality semantics of the NDArray implementation is flawed.

Basically, when constructing and comparing identity matrices, two matrices that are clearly not equivalent by any numerical definition will be erroneously be reported to be equivalent by  `e==`, and `equals`.

I've constructed a set of [test cases](https://github.com/RadicalZephyr/core-matrix-equality-tests/blob/988408717194e23606582385acfa2cba45e2853c/test/matrix_test/matrix_equals_test.clj) using `clojure.test` in a minimal project to demonstrate the strange behavior.

**Comment by mikera** [comment] 2015-08-24 04:37
Thanks for the report... yes that certainly looks like a bug at first glance.

@si14 any idea what is happening here?

Is anyone able to take a crack at a patch that:

a) Incorporates the linked test cases
b) Fixes the NDArray behaviour

**Comment by fyquah** [comment] 2015-08-26 22:38
It seems that the problem is related to the `mp/PMatrixEquality` implementation for `dimension = 2` ndarrays (aka matrices).

``` clojure
user=> (m/e== (m/array :ndarray [[1 0 0] [0 0 0] ]) (m/array :ndarray [[1 0 0] [0 9 0]]))
true
user=> (m/e== (m/array :ndarray [[1 0 0] [0 0 0] ]) (m/array :ndarray [[1 0 0] [0 9 0]]))
true
user=> (m/e== (m/array :ndarray [[[1 0 0] [0 0 0] ]]) (m/array :ndarray [[[1 0 1] [0 9 0]]]))
false
user=> (m/e== (m/array :ndarray [[1 0 0]]) (m/array :ndarray [[1 0 0]]))
true
user=> (m/e== (m/array :ndarray [1 0 0]) (m/array :ndarray [1 0 1]))
false
```

It seems that when it tests for 2D array-equality, it checks only the first row.

From what I understand https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/impl/ndarray.clj#L737-L746 , seems to be looping through through the matrix's indices, advancing `step-col-a` or `step-col-b` every run

I think `step-row-a (- (aget strides 0) (* step-col-a ncols))` should be `step-row-a (- (aget strides 0) (* step-col-a (dec ncols)))` ( dito step-row-b ).

**Comment by mikera** [comment] 2015-08-27 03:43
OK thanks @fyquah95 for the investigation! The problem is definitely with this code. 

Actually there were a couple of other issues with this code, I just pushed an update which I think fixes these.

**Comment by mikera** [comment] 2015-08-27 03:45
@RadicalZephyr could you re-test with the latest develop branch?

**Comment by RadicalZephyr** [comment] 2015-08-27 23:57
I would be happy to, but I'm having issues even getting the newest `develop` branch installed.  I tried just running `lein install` but that errors like so:

```
Compiling 2 source files to /Users/geoff/src/core.matrix/target/classes
/Users/geoff/src/core.matrix/src/test/java/clojure/core/matrix/APITest.java:3: error: package mikera.cljunit does not exist
import mikera.cljunit.ClojureTest;
                     ^
/Users/geoff/src/core.matrix/src/test/java/clojure/core/matrix/APITest.java:5: error: cannot find symbol
public class APITest extends ClojureTest {
                             ^
  symbol: class ClojureTest
/Users/geoff/src/core.matrix/src/test/java/clojure/core/matrix/APITest.java:7: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors
Compilation of Java sources(lein javac) failed.
```

**Comment by mikera** [comment] 2015-08-28 05:44
Hmmmm not sure what Leiningen is doing here, seems to be some kind of classpath issue where it is not including the dev dependencies. I will take a look at it.

Maven is the standard build tool used for core.matrix BTW - `mvn install` should do the trick if you have Maven installed.

**Comment by RadicalZephyr** [comment] 2015-08-29 18:40
ah, good to know.  I'll do that then.

**Comment by RadicalZephyr** [comment] 2015-08-29 19:39
Okay, got the new version installed and it looks like the issue is fixed both in the project I originally encountered it in and in my test project linked above.

Thanks!

**Comment by mikera** [comment] 2015-08-30 06:46
Great, thanks for confirming! I will close this issue and make a new release soon

**Closed as completed by mikera** 2015-08-30 06:46 UTC
Labels: bug
