### ISSUE TITLE
length not working

### ISSUE THREAD

**Issue by grtlr** [mikera/core.matrix#33] opened 2013-03-09 09:53 UTC
It seems to me that the `length` implementation is not found correctly.

```
(use 'core.matrix)
(length [1 1])
```

Returns an `IllegalArgumentException`:

```
java.lang.IllegalArgumentException: No implementation of method: :length of protocol: #'clojure.core.matrix.protocols/PVectorOps found for class: clojure.lang.PersistentVector
```

I don't fully understand how the protocols of the _matrix-api_ work yet, maybe you can point me in the right direction? 

Thank you!

**Comment by mikera** [comment] 2013-03-09 11:44
Hmm `length` is working fine for me. What Clojure version are you using?

Basic design is:
- The functions like `length` are in clojure.core.matrix
- These functions delegate to a protocol, defined in clojure.core.matrix.protocols
- Different implementations extend the protocols to their own types, e.g. clojure.core.matrix.impl.persistent-vector
- In the absence of an implementation extending the prodocol, default (fallback) implementations are defined in clojure.core.matrix.impl.default

**Comment by grtlr** [comment] 2013-03-09 11:58
Ok, this makes sense. 
I've tried the above with `clojure 1.4` and `clojure 1.5` in the `repl` and in _Light Tables_ `instarepl`. Both give me the exception from my initial post. When I call `(doc length)` it shows me the correct documentation for the function. I did all this with a repl in my own project, which is using the `core.matrix` from _clojars_.
I haven't found a way yet to connect to `core.matrix` directly via the `repl`. When I do `lein repl` int the root of the _matrix-api_ project and do `(use 'core.matrix)` it says it couldn't locate 

```
core/matrix__init.class or core/matrix.clj on classpath
```

How would I load the _matrix-api_ project into the `repl`?

**Comment by mikera** [comment] 2013-03-09 12:49
It should be `clojure.core.matrix` in the latest version since we changed the namespaces in preparation for being part of contrib..... problem with the use statement perhaps?

**Comment by grtlr** [comment] 2013-03-09 13:23
This is also something I tried. After doing `lein repl` in the _matrix-api_ root and doing

```
(use 'clojure.core.matrix)
```

I get the following `FileNotFoundException`:

```
FileNotFoundException Could not locate clojure/core/matrix__init.class or clojure/core/matrix.clj on classpath:   clojure.lang.RT.load (RT.java:432)
```

**Comment by ejackson** [comment] 2013-03-09 14:27
Is length not better named norm ?

**Comment by mikera** [comment] 2013-03-09 14:28
Hmmm what about `magnitude` as well?

**Comment by ejackson** [comment] 2013-03-09 14:30
I'd say norm is the more standard mathsy term.

**Comment by ejackson** [comment] 2013-03-09 14:30
although I guess we're talking specifically about the 2-norm here.

**Comment by mikera** [comment] 2013-03-09 15:38
Euclidean (2-norm) usually gets called `magnitude` doesn't it?

http://en.wikipedia.org/wiki/Norm_(mathematics)

We might want a separate `(norm p some-vector)` function to do Lp norms.....

**Comment by ejackson** [comment] 2013-03-09 15:51
I've not heard this frequently, but maybe in different circles :)

I like

``` clojure
(norm
  ([v] (norm v 2))
  ([v p] ....)
```

**Comment by mikera** [comment] 2013-03-10 09:47
Yeah, an overloaded version of norm works fine for me.

**Comment by grtlr** [comment] 2013-03-10 10:46
Isn't `norm` just a general term for a function that returns a scalar (with some additional requirements), yet it is not necessarily defined how such a function should look like? I think most people that will use the library will expect a `length` or `magnitude` function that represents the _euclidean norm_. 
Nevertheless it might be a good idea to support other norms as well.

**Comment by mikera** [comment] 2013-04-15 06:33
Closing this as the issue is fixed.

**Closed as completed by mikera** 2013-04-15 06:33 UTC
