### ISSUE TITLE
Add mutative counterparts in API

### ISSUE THREAD

**Issue by si14** [mikera/core.matrix#56] opened 2013-07-31 22:13 UTC
There are a few protocols without mutative counterparts, namely:
- PNegation
- PExponent
- PSquare

Is it by design?

**Comment by mikera** [comment] 2013-08-22 14:37
Not particularly by design. 

If mutable versions of these functions are sensible / required then we should add them.

Note that some API functions can be implemented via alternative protocols, for example `(negate! a)` could be implemented the same as `(scale! a -1)`

**Comment by mikera** [comment] 2013-08-26 05:57
Hi Dmitry, closing this as the original question is answered and there doesn't appear to be a specific action. If you want to create some patches to add these things then go for it!

**Closed as completed by mikera** 2013-08-26 05:57 UTC
