### ISSUE TITLE
Possible bug with (mmul ^NDArrayDouble x ^APersistentVector y)

### ISSUE THREAD

**Issue by aphyr** [mikera/core.matrix#97] opened 2014-01-10 21:44 UTC
``` clj
(defn poly-design-matrix
  "Given a polynomial degree (say 2 for a quadratic model), and a vector x of
  independent observations [x1 x2 x3 ...], generate a matrix like:

  [1 x1 x1^2]
  [1 x2 x2^2]
  [1 x3 x3^2]"
  [degree x]
  (->> (range (inc degree))
       (map (partial m/pow x))
       m/matrix
       m/transpose))

user=> (def y [1 4 9 16])
#'user/y
user=> (def X (poly-design-matrix 2 [1 2 3 4]))
#'user/X
```

Now let's do a linear regression for y = Xb + e, solving for b.

``` clj
user=> (def X' (m/transpose X))
#'user/X'
user=> (def tmp (m/mmul (m/inverse (m/mmul X' X)) X'))
#'user/tmp
user=> tmp
#<NDArrayDouble [[2.249999999999946 -0.7499999999999645 -1.2499999999999591 0.7499999999999574] [-1.5499999999999496 1.1499999999999648 1.3499999999999606 -0.9499999999999638] [0.24999999999999023 -0.24999999999999312 -0.249999999999992 0.24999999999999378]]>
```

OK so I'm a tad surprised that despite the implementation being PersistentVector, `inverse` spat out an NDArrayDouble, but I bet it's more efficient this way, and the protocols mean I don't have to care, right? This is a 3x4 matrix; we should be able to multiply it by y, which is a 4-vector.

``` clj
user=> (m/mmul tmp y)

RuntimeException Reshape not possible: insufficient elements for shape: (4) have: (-2.2737367544323206E-13 1.3500311979441904E-13 0.9999999999999902)  clojure.core.matrix.impl.default/eval6937/fn--6938 (default.clj:1252)
```

Odd. But this works:

``` clj
user=> (m/mmul (m/coerce [] tmp) y)
[-2.2737367544323206E-13 1.3500311979441904E-13 0.9999999999999902]
```

Something to do with the type of the matrix, perhaps? It's been hard for me to figure out what, exactly, core.matrix's approach to matrix and vector representation is--I think matrixes are represented as rows and then columns--but why is a reshape even necessary? It also looks like vectors are automatically coerced to Nx1 or 1xN matrices, so I shouldn't have to transpose here--didn't see any row-vec or col-vec constructors, anyway, but maybe I misunderstood. Thoughts?

**Comment by mikera** [comment] 2014-01-11 13:14
The reason it spits out an NDArrayDouble is a bit obtuse: currently only NDArray has an "inverse" operation coded (Vectorz has one too of course, but that's not in the standard core.matrix set of implementations)

I've confirmed your exception is a bug in NDArray, I'll push out a fix today.

**Comment by mikera** [comment] 2014-01-11 13:41
Regarding the differences between vectors and matrices and how they work, this page is worth a look (and please send in changes if you think it could be improved!)

https://github.com/mikera/core.matrix/wiki/Vectors-vs.-matrices

**Comment by mars0i** [comment] 2014-01-11 19:30
I have two suggestions for the page on vectors vs. matrices.  (What's the best way to propose changes to wiki pages, by the way?  Create issues?  Pull requests?)

I'd suggest adding a remark that `mmul` will in effect treat  a 1D core.matrix vector as if it was row vector when it's the first argument to `mmul`, and as it if's a column vector when it's the second argument to `mmul`.  In this way, `mmul` captures the mathematical relationship between inner product, and matrix multiplication of row and column vectors.  Note that you can get different shapes back depending on whether 1D, 1xN, or Nx1 structures are used (e.g. 0D, 1D, or 1x1 when representations of vectors are multiplied), but the numeric content of the result would be the same.  

(That's not news, obviously; I'm just saying that I think this is what could be made explicit.)

I also think it might be worth mentioning the 1xN and Nx1 representations of vectors in the initial list of matrix properties.  I think it's easy to miss the point in the middle of the page that mathematical vectors can be represented either as core.matrix vectors or 1xN and Nx1 matrices.  

(I was tripped up briefly because I forgot this point.  I think that there may continue to be confusion, now and then, among people who are new to core.matrix.  So maybe it wouldn't hurt to emphasize the interplay between the two kinds of representations.)

I'd be happy to propose some specific text, with examples, if that seems useful.

Hmm, maybe it would be worth noting the behavior of first-arg and second-arg 1D vectors in the docstring for `mmul`.  That's going to be the only documentation that some people see.

**Comment by mikera** [comment] 2014-01-11 21:55
Great ideas!

Probably easiest if you just fire a pull request with any changes? I'll generally just merge any PR that looks like an obvious improvement.

**Comment by mikera** [comment] 2014-01-12 00:23
Closing this as the original defect is now fixed.

**Closed as completed by mikera** 2014-01-12 00:23 UTC
Labels: bug

**Comment by aphyr** [comment] 2014-01-12 00:26
Woot! Thanks. :)
